# Econometrics

# Fifth Session

# Ordinary Least Squares Using Matrices

## An example

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [25]:
sheet_name = 'HW'
file_path = 'first session.xlsx'

data_hw = pd.read_excel(file_path, sheet_name) #header = None means no header exists, but in our file we headers

In [27]:
data_hw.head()

First  Second
0    1.5    2.85
1    2.0    3.60
2    2.5    4.15
3    3.0    5.00
4    3.5    5.85

In [31]:
(data_hw['First'] + data_hw['First']).tail()

34    37.0
35    38.0
36    39.0
37    40.0
38    41.0
Name: First, dtype: float64

## adding intercept

In [34]:
S = np.array([[2], [3], [4]])
S

array([[2],
       [3],
       [4]])

In [36]:
np.ones(2)

array([1., 1.])

In [42]:
S.shape

(3, 1)

In [44]:
S.shape[0]

3

In [46]:
np.ones(S.shape[0])

array([1., 1., 1.])

## np.column_stack()

In [62]:
np.column_stack((S, S))

array([[2, 2],
       [3, 3],
       [4, 4]])

In [64]:
np.column_stack((S, S, S))

array([[2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [68]:
S_with_ones = np.column_stack((np.ones(S.shape[0]), S))
S_with_ones

array([[1., 2.],
       [1., 3.],
       [1., 4.]])

## Running the OLS

### $\beta = (X'X)^{-1} X'Y$

In [71]:
X = data_hw['First']
X.head()

0    1.5
1    2.0
2    2.5
3    3.0
4    3.5
Name: First, dtype: float64

In [73]:
X.shape

(39,)

In [114]:
type(X)

pandas.core.series.Series

In [89]:
X_with_intercept = np.column_stack((np.ones(X.shape[0]), X))
X_with_intecept[0:5]

array([[1. , 1.5],
       [1. , 2. ],
       [1. , 2.5],
       [1. , 3. ],
       [1. , 3.5]])

In [116]:
type(X_with_intercept)

numpy.ndarray

In [91]:
X_prime = X_with_intercept.T

In [101]:
X_prime[1][1:5]

array([2. , 2.5, 3. , 3.5])

In [103]:
X_prime_X = X_prime @ X_with_intercept
X_prime_X

array([[  39.,  429.],
       [ 429., 5954.]])

In [105]:
inverse_of_X_prime_X = np.linalg.inv(X_prime_X)
inverse_of_X_prime_X

array([[ 0.12361673, -0.00890688],
       [-0.00890688,  0.00080972]])

In [107]:
Y = data_hw['Second']
estimators = inverse_of_X_prime_X @ X_prime @ Y
estimators

array([0.25036437, 1.56744939])

## Introduction to f-string

In [110]:
print("intercept: ", estimators[0])
print("slope: ", estimators[1])

intercept:  0.25036437246963894
slope:  1.5674493927125515


In [112]:
print(f"Intercept: {estimators[0]}")
print(f"coefficient: {estimators[1]}")

Intercept: 0.25036437246963894
coefficient: 1.5674493927125515


## Tranforming the data to numpy array right from the beginning

In [119]:
sheet_name = 'HW'
file_path = 'first session.xlsx'

data_hw = pd.read_excel(file_path, sheet_name)

In [121]:
data_hw['First'].values

array([ 1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,
        7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. ,
       12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. , 17.5,
       18. , 18.5, 19. , 19.5, 20. , 20.5])

In [123]:
data_hw['First'].values.shape

(39,)

In [129]:
data_hw['First'].values.reshape(-1, 1)[1:5]

array([[2. ],
       [2.5],
       [3. ],
       [3.5]])

In [569]:
X = data_hw['First'].values.reshape(-1, 1)
X.shape

(39, 1)

In [571]:
Y = data_hw['Second'].values.reshape(-1, 1)
Y.shape

(39, 1)

In [573]:
type(X)

numpy.ndarray

In [574]:
X = np.column_stack((np.ones(X.shape[0]), X))
X[0:3]

array([[1. , 1.5],
       [1. , 2. ],
       [1. , 2.5]])

In [577]:
X_transpose = X.transpose()

In [579]:
inverse_X_transpose_X = np.linalg.inv(X_transpose @ X)
inverse_X_transpose_X

array([[ 0.12361673, -0.00890688],
       [-0.00890688,  0.00080972]])

In [581]:
estim = inverse_X_transpose_X @ X_transpose @ Y
print(f"Intercept: {estim[0]}")
print(f"coefficient: {estim[1]}")

Intercept: [0.25036437]
coefficient: [1.56744939]


## Calculating the Sum of Squared Residuals (1st Method)

In [584]:
Y_hat = X @ estim
Y_hat[1:5]

array([[3.38526316],
       [4.16898785],
       [4.95271255],
       [5.73643725]])

In [586]:
residuals = Y - Y_hat
residuals[1:5]

array([[ 0.21473684],
       [-0.01898785],
       [ 0.04728745],
       [ 0.11356275]])

In [588]:
SSR = residuals.T @ residuals
print(f"e'e or sum squared residulas is equal to {SSR}")

e'e or sum squared residulas is equal to [[0.26915789]]


## M Matrix that is idempotent and symmetric

### $ e = Y - \hat Y = Y - X(X'X)^{-1} X' Y = [I - X(X'X)^{-1} X']Y = MY$

### $M^2 = M$

In [591]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [593]:
X.shape

(39, 2)

In [595]:
X.shape[0]

39

In [597]:
I = (np.eye(X.shape[0]))

In [601]:
M = I - X @ inverse_X_transpose_X @ X_transpose
M[0:5, 4: 7]

array([[-0.08333333, -0.07948718, -0.07564103],
       [-0.0802969 , -0.07665317, -0.07300945],
       [-0.07726046, -0.07381916, -0.07037787],
       [-0.07422402, -0.07098516, -0.06774629],
       [ 0.92881242, -0.06815115, -0.06511471]])

In [624]:
squared_M = M @ M
squared_M[0:5, 0:5]

array([[ 0.90128205, -0.09487179, -0.09102564, -0.08717949, -0.08333333],
       [-0.09487179,  0.90877193, -0.08758435, -0.08394062, -0.0802969 ],
       [-0.09102564, -0.08758435,  0.91585695, -0.08070175, -0.07726046],
       [-0.08717949, -0.08394062, -0.08070175,  0.92253711, -0.07422402],
       [-0.08333333, -0.0802969 , -0.07726046, -0.07422402,  0.92881242]])

In [626]:
(squared_M @ M @ M)[0:5, 0:5]

array([[ 0.90128205, -0.09487179, -0.09102564, -0.08717949, -0.08333333],
       [-0.09487179,  0.90877193, -0.08758435, -0.08394062, -0.0802969 ],
       [-0.09102564, -0.08758435,  0.91585695, -0.08070175, -0.07726046],
       [-0.08717949, -0.08394062, -0.08070175,  0.92253711, -0.07422402],
       [-0.08333333, -0.0802969 , -0.07726046, -0.07422402,  0.92881242]])

## Calculating the Sum of Squared Residuals (2nd Method)

### $e'e = Y'MY$

In [229]:
(M @ Y)[:5,]

array([[ 0.24846154],
       [ 0.21473684],
       [-0.01898785],
       [ 0.04728745],
       [ 0.11356275]])

In [231]:
e_prime_e = Y.T @ M @ Y
e_prime_e

array([[0.26915789]])

In [233]:
if e_prime_e == SSR:
    print("Both methods calculated the same value")
else:
    print("each method calculated a different value")

each method calculated a different value


## Estimating the intercept and coefficient for a population

### first we Create two populations for independent variables

In [473]:
np.random.seed(37)
n = 10000
X1 = np.random.laplace(0,14, n)
X1

array([ 30.77429418,  -1.0431678 , -13.341727  , ...,  22.37857966,
        10.53883427, -31.83335808])

In [475]:
X2 = np.random.rand(n, 1)
print(X2.shape)
X2

(10000, 1)


array([[0.35886978],
       [0.78715143],
       [0.97868659],
       ...,
       [0.80822939],
       [0.24943065],
       [0.53917845]])

### Setting the population parameters

In [478]:
alpha = 0.7
beta1 = 1.2
beta2 = 1.7

Y = alpha + beta1 * X1 + beta2 * X2
Y

array([[ 38.23923164,   0.05827726, -14.69999377, ...,  28.16437422,
         13.95667975, -36.88995106],
       [ 38.96731044,   0.78635606, -13.97191498, ...,  28.89245302,
         14.68475855, -36.16187227],
       [ 39.29292022,   1.11196584, -13.64630519, ...,  29.2180628 ,
         15.01036833, -35.83626248],
       ...,
       [ 39.00314297,   0.82218859, -13.93608244, ...,  28.92828555,
         14.72059108, -36.12603973],
       [ 38.05318512,  -0.12776926, -14.88604029, ...,  27.9783277 ,
         13.77063323, -37.07599758],
       [ 38.54575638,   0.364802  , -14.39346904, ...,  28.47089896,
         14.26320449, -36.58342633]])

In [479]:
X1.flatten().shape

(10000,)

## We assume that the population is deterministic rather than stochastic, meaning that Y is fully explained by X1 and X2.

In [483]:
Y_pop = alpha + beta1 * X1.flatten() + beta2 * X2.flatten()
Y_pop

array([ 38.23923164,   0.78635606, -13.64630519, ...,  28.92828555,
        13.77063323, -36.58342633])

## Another assumption is that, when modeling Y based on explanatory variables, we do not have access to X2 and can only model Y using X1. Therefore, we must account for a stochastic term when modeling Y based on X1—this term, epsilon, follows a stochastic process.

In [486]:
epsilon = np.random.normal(0, 1, n)
Y_observed = alpha + beta1 * X1.flatten() + epsilon

### We sample `X1` and `Y_observed` to simulate real-world limitations where data access is restricted. Indices are randomly chosen without replacement to form subsets for analysis. Since `X2` is unavailable, we introduce a stochastic term to adjust for missing explanatory power. In reality, access to `X1` and `Y` may also be limited, requiring such sampling approaches.

In [520]:
sample_size = 100
indices = np.random.choice(10000, sample_size, replace=False)

X1_sample = X1[indices]
Y_sample = Y_observed[indices]

In [522]:
Y_sample.shape

(100,)

In [530]:
X1_sample.shape

(100,)

In [532]:
X1_sample_reshaped = X1_sample.reshape(100, 1)
X1_sample_reshaped.shape

(100, 1)

In [536]:
Y_sample_reshaped = Y_sample.reshape(100, 1)
Y_sample_reshaped.shape

(100, 1)

### ADDING INTERCEPT

In [538]:
X1_sample_reshaped_with_intercept = np.column_stack((np.ones(X1_sample_reshaped.shape[0]), X1_sample_reshaped))
X1_sample_reshaped_with_intercept.shape

(100, 2)

### $\beta = (X'X)^{-1} X'Y$

In [540]:
XTX_inv = np.linalg.inv(X1_sample_reshaped_with_intercept.T @ X1_sample_reshaped_with_intercept)

In [542]:
XTY = X1_sample_reshaped_with_intercept.T @ Y_sample_reshaped

In [544]:
intercept_and_slope = XTX_inv @ XTY

In [546]:
intercept_and_slope

array([[0.72939531],
       [1.2047024 ]])

In [611]:
print(f"Intercept: {intercept_and_slope[0]}")
print(f"coefficient: {intercept_and_slope[1]}")

Intercept: [0.72939531]
coefficient: [1.2047024]


# Exercise

## 1. Use the second sheet of the Excel file and complete the following steps:

### - Calculate the intercept and coefficient using matrix operations.
### - Compute the Sum of Squared Residuals (SSR) using two methods discussed in this session.

### 2. Define two variables using random generation functions, then create a new variable as their linear combination (e.g., $2x_1 + 3x_2 = y$) 

### - Use np.random.choice() to sample random values from y created in the second exercise. Also, sample vectors from that y. 
### - Construct a 3×3 matrix using the sampled values from 𝑦.