# Economterics

# Forth Session

## Matrices, For-loops, Conditionals

## numpy library

In [50]:
import numpy as np

In [52]:
np.e

2.718281828459045

In [54]:
np.pi

3.141592653589793

## Creating ranges of numbers

In [56]:
L = [1, 2, 3, 4]
L

[1, 2, 3, 4]

## using range() built-in function

In [58]:
range(5)

range(0, 5)

#### tuple() or list()

In [61]:
tuple(range(5))

(0, 1, 2, 3, 4)

In [63]:
list(range(5))

[0, 1, 2, 3, 4]

In [71]:
even = list(range(0, 10, 2))
print(even)

[0, 2, 4, 6, 8]


In [75]:
odd = list(range(1, 21, 2))
print(odd)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


## Control Flow Structure

### for-loop

In [79]:
a = 1 #global variable

In [81]:
a

1

In [87]:
print(a)

1


In [89]:
for عدد in range(1, 8): #عدد is a local variable
    print(عدد)

1
2
3
4
5
6
7


In [91]:
عدد

7

In [95]:
for number in range(1, 8):
    print(number ** 2)

1
4
9
16
25
36
49


In [97]:
for i in range(1, 8):
    i += 8
    print(i)

9
10
11
12
13
14
15


### conditional

In [100]:
w = ["a", 5, "hello", 9, (8, 9)]

In [106]:
for element in w:
    if element == "hello":
        print(w.index(element))

2


In [108]:
w.index((8, 9))

4

In [110]:
for t in w[4]:
    print(t)

8
9


In [112]:
for t in w[4]:
    print(t ** 2)

64
81


In [114]:
w

['a', 5, 'hello', 9, (8, 9)]

## using np.linspace()

In [118]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [120]:
range2 = np.linspace(1, 10, 10, dtype = int)
print(range2)

[ 1  2  3  4  5  6  7  8  9 10]


In [124]:
for s in range2:
    if s % 2 == 0:
        print("Even")

Even
Even
Even
Even
Even


## Using else

In [129]:
for s in range2:
    if s % 2 == 0:
        print("Even")
    else:
        print("odd")

odd
Even
odd
Even
odd
Even
odd
Even
odd
Even


In [133]:
list(range(0.1, 0.9))

TypeError: 'float' object cannot be interpreted as an integer

In [388]:
np.linspace(0.1, 0.8, 10)

array([0.1       , 0.17777778, 0.25555556, 0.33333333, 0.41111111,
       0.48888889, 0.56666667, 0.64444444, 0.72222222, 0.8       ])

In [137]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### range() is exclusive but np.linspace() is inclusive

In [139]:
np.linspace(0, 1, 5, endpoint = False)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [141]:
np.linspace(0, 1, 5, endpoint = False, dtype = int)

array([0, 0, 0, 0, 0])

In [195]:
np.linspace(0, 5, 10, endpoint = False, dtype = int)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

## np.linspace() type

In [144]:
p = np.linspace(0, 1, 5, endpoint = False, dtype = int)
type(p)

numpy.ndarray

In [150]:
#dir(p)

### .reshape() method

In [160]:
arayesh1 = np.linspace(1, 10, 10)
arayesh1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [158]:
arayesh2 = np.linspace(1, 10, 10).reshape(2, 5)
print(arayesh2)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


## np.arange()

In [164]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [166]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [172]:
#help(np.arange)

In [170]:
np.arange(1, 10, 3)

array([1, 4, 7])

## np.array()

In [174]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [176]:
np.array(range(0, 10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [182]:
np.array(range(1, 10)).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## creating a matrix manually

In [391]:
np.array([1, 2, 3, 4, 5], [1, 2, 3, 4, 5]) #wrong syntax bcs python thinks there are two arguments given

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [199]:
np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

### .resize() method

In [206]:
arayesh4 = np.arange(10)
print("without resizing", arayesh4)
arayesh4.resize(2, 5)
print(arayesh4)

without resizing [0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


#### .ravel()

In [211]:
matrix = np.array([[8, 9, 1], [2, 7, 4], [6, 4, 3]])
matrix

array([[8, 9, 1],
       [2, 7, 4],
       [6, 4, 3]])

In [213]:
matrix.ravel()

array([8, 9, 1, 2, 7, 4, 6, 4, 3])

In [215]:
matrix

array([[8, 9, 1],
       [2, 7, 4],
       [6, 4, 3]])

### .flatten()

In [218]:
matrix.flatten()

array([8, 9, 1, 2, 7, 4, 6, 4, 3])

In [220]:
matrix

array([[8, 9, 1],
       [2, 7, 4],
       [6, 4, 3]])

### .transpose() or .T

In [224]:
matrix.T

array([[8, 2, 6],
       [9, 7, 4],
       [1, 4, 3]])

In [226]:
matrix.transpose()

array([[8, 2, 6],
       [9, 7, 4],
       [1, 4, 3]])

## np.eye()

In [237]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## np.zeros()

In [243]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Random Number generators

#### np.random.rand() generates random number from a uniform distribution over [0, 1)

In [247]:
np.random.rand()

0.15727320817971535

In [254]:
np.random.rand(5)

array([0.01215677, 0.67401992, 0.0518358 , 0.54885867, 0.28763273])

In [403]:
np.random.rand(2,2)

array([[0.63316204, 0.40657968],
       [0.47604698, 0.86989094]])

## np.random.seed()

In [272]:
np.random.seed(5)
np.random.rand(2,2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091]])

#### np.random.randn() generates from a standard normal distribution

In [278]:
np.random.randn(5)

array([-0.35882895,  0.6034716 , -1.66478853, -0.70017904,  1.15139101])

In [286]:
np.random.randn(5, 2)

array([[-0.20211818, -0.59835993],
       [-0.2434197 ,  2.08851469],
       [ 0.34691933,  0.74572695],
       [ 0.77690759,  1.01842113],
       [ 1.06135144, -0.71046645]])

#### np.random.randint() generates random integers from a specified range

np.random.randint(low, high, size)

np.random.randint(low, high, (rows, columns))


In [290]:
np.random.randint(1, 100, 5)

array([ 1, 35, 79, 52, 31])

In [294]:
np.random.randint(1, 100, (3, 3))

array([[90, 58, 18],
       [95, 65, 29],
       [ 9, 15, 65]])

#### np.random.uniform() generates from a uniform distribution over a specfied range.

In [296]:
np.random.uniform(1, 400, 5)

array([386.03365947, 228.81911153, 121.70472689, 330.45662477,
       264.10749486])

In [298]:
np.random.uniform(1, 400, (2, 2))

array([[394.61407512,  43.8883239 ],
       [232.78649253, 189.65843387]])

#### np.random.choice()

In [306]:
population = [17, 22, 24, 23, 25, 29, 14, 16, 3.14]
random_number = np.random.choice(population)
print(random_number)

17.0


In [312]:
random_number2 = np.random.choice(population, size = 3)
print(random_number2)

[16. 23. 16.]


In [322]:
random_number3 = np.random.choice(population, size = 3, replace = False)
print(random_number3)

[17. 22. 16.]


## Slicing

In [324]:
matrix2 = np.array([0, 1, 2, 5, 6, 7])
matrix2[1:3]

array([1, 2])

In [328]:
matrix2[::2]

array([0, 2, 6])

In [330]:
matrix2[::3]

array([0, 5])

In [336]:
slice_example = matrix2[matrix2 > 2]
slice_example

array([5, 6, 7])

## Solving a system of equations using cramer's rule



\begin{cases}
3x + 2y = 10 \\
5x - y = 7
\end{cases}





In [358]:
A = np.array([[3, 2], [5, -1]])
A

array([[ 3,  2],
       [ 5, -1]])

In [360]:
B = np.array([10, 7])
B

array([10,  7])

## calculating the determinant of the matrix: np.linalg.det()

In [363]:
det_A = np.linalg.det(A)
det_A

-13.0

In [365]:
A_x = A.copy()
B_x = A.copy()

### for finding x, we want to replace the first column of matrix A with matrix B

In [367]:
A_x

array([[ 3,  2],
       [ 5, -1]])

In [372]:
A_x[:, 0]

array([3, 5])

In [376]:
A_x[:, 0] = B
print(A_x)

[[10  2]
 [ 7 -1]]


In [378]:
np.linalg.det(A_x)

-24.000000000000014

## finding x

In [380]:
x = np.linalg.det(A_x) / det_A
print(x)

1.8461538461538471


### inverse -> np.linalg.inv()

In [408]:
np.linalg.inv(A)

array([[ 0.07692308,  0.15384615],
       [ 0.38461538, -0.23076923]])

# Exercises

## 1. Calculate y for the given system in the notebook using Cramer's Rule.

## 2. define two squre matrices. Multiply them once using * and one time using @. Explain the difference between @ and *.

## 3. Multiply this matrix by its transpose. What is the name of this matrix?

$A =
\begin{bmatrix}
\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\
-\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}}
\end{bmatrix}$




## 4. Use np.trace and calcualte the trace of the following matrix.

$A =
\begin{bmatrix}
5 & 2 & 4\\
0 & 7 & 8 \\
0 & 0 & 2
\end{bmatrix}$

## 5. Solve the system of equations in this notebook using $AX=B$ then $X = A^{-1} B$

## 6. Create a random 2 by 2 matrix and calculate its determinant manually.

## 7. Calculate the determinant of the following matrix and write a code snippet that checks if the determinant is equal to 0. If it is, the code should indicate that the matrix is singular.

$A =
\begin{bmatrix}
1 & 2 \\
2 & 4
\end{bmatrix}$

## 8. A student has defined the following function incorrectly. Fix her mistake.

In [480]:
import numpy as np

def solve_system(A, B):
    if np.linalg.det(A) == 0:
        print("Matrix A is singular!")
        return None
    
    X = np.linalg.inv(A) * B 
    
    return X

# Example usage
A = np.array([[2, 1], [5, 3]])
B = np.array([1, 2])

solution = solve_system(A, B)
print("Solution:", solution)


Solution: [[ 3. -2.]
 [-5.  4.]]


## 9. A restaurant offers 5 dishes. Use np.random.choice() to generate a list of 100 customer orders, then count how many times each dish was ordered.

## 10. Create a list of lottery ticket numbers and assign each one a probability (some tickets are more likely to be drawn). Use np.random.choice() to simulate 5 draws with weighted probabilities.